run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - linters
    - staticcheck
    - typecheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - decorder
    - dogsled
    - dupword
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exportloopref
    - forbidigo
    - gci
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godot
    - godox
    - gofmt
    - goheader
    - goimports
    - gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - importas
    - interfacebloat
    - ireturn
    - loggercheck
    - maintidx
    - misspell
    - mnd
    - nakedret
    - nctx
    - nestif
    - nilerr
    - nilnil
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - stylecheck
    - tenv
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - undeclaredname
    - unparam
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck

linters-settings:
  varnamelen:
    min-name-length: 2
  gocyclo:
    min-complexity: 10
  gocognit:
    min-complexity: 10

issues:
  exclude-rules:
    - path: _test\.go$
      linters:
        - varnamelen
        - gocyclo
        - gocognit
